name: "tagged-release"

on: 
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  tagged-release:
    name: 'Tagged Release'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: 'npm'

      - name: 'Install dependencies'
        run: npm ci
      
      - name: 'Build extension'
        run: npm run build
      
      - name: 'Chrome: Compress to Zip'
        run: |
          sudo apt-get install -y zip
          rm manifest.json
          mv chrome-manifest.json manifest.json
          zip -r asb-auto-subs-chrome dist html css imgs manifest.json

      - name: 'Firefox: Compress to Zip'
        run: |
          sudo apt-get install -y zip
          rm manifest.json
          mv firefox-manifest.json manifest.json
          zip -r asb-auto-subs-firefox dist html css imgs manifest.json

      - uses: 'marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0' # v1.2.1
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            *.zip
